alias g='git'
alias gb='git branch'
alias gg='git grep -n'
alias gswp='git branch | grep -v "master" | xargs git branch -D'
alias m='make -j8'
alias tmx='tmux'
alias uuid='uuidgen | tr -d - | tr "[:upper:]" "[:lower:]"'
alias v='vim'
